cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

goza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import ProductsSitemap

sitemaps = {'posts': ProductsSitemap, }

# admin.autodiscover()
# admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),

    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),

    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('tinymce/', include('tinymce.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search/', views.products_search, name='products_search'),
    path('<slug:category_slug>', views.category_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:slug>/<int:pk>/', views.product_detail, name='product_detail'),

]

shop/models.py
from django.db import models
from mptt.models import MPTTModel
from mptt.fields import TreeForeignKey
from taggit.managers import TaggableManager
from django.urls import reverse


class Category(MPTTModel):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    name = models.CharField('Назва категорії', max_length=200, db_index=True)
    slug = models.SlugField("url", max_length=200, unique=True)
    position = models.IntegerField('Порядковий номер', blank=True, null=True)
    image = models.ImageField('Обкладинка для категорій', upload_to='categories/%Y/%m/%d', blank=True, null=True)
    small_image = models.ImageField('Обкладинка на головну', upload_to='categories/%Y/%m/%d', blank=True, null=True)
    available_on_main = models.BooleanField('Закріпити на головній?', default=False)

    class Meta:
        ordering = ('name',)
        verbose_name = 'категорія'
        verbose_name_plural = 'категорії'

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        full_path = [self.name]
        k = self.parent
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return '  /  '.join(full_path[::-1])

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[str(self.slug)])


class Brand(models.Model):
    name = models.CharField('Ім\'я', max_length=255)
    image = models.ImageField('Фото', upload_to='brands/', blank=False)

    class Meta:
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'
        ordering = ('name',)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name='Назва категорії', related_name='products',
                                 on_delete=models.CASCADE)

    vendor_code = models.CharField('Артикул', max_length=200, db_index=True)
    name = models.CharField('Назва товару', max_length=200, db_index=True)
    slug = models.SlugField('url', max_length=200, db_index=True)
    full_image = models.ImageField('Велике фото', upload_to='products/%Y/%m/%d', blank=True)
    small_image = models.ImageField('Мале фото', upload_to='products/%Y/%m/%d', blank=True)
    small_description = models.TextField("Короткий опис", blank=True)
    description = models.TextField('Опис товару', blank=True)
    price = models.DecimalField('Кінцева ціна', max_digits=10, decimal_places=2)
    old_price = models.DecimalField('Cтара ціна (перекреслена)', max_digits=10, decimal_places=2, blank=True)
    available = models.BooleanField('Доступність', default=True)
    tags = TaggableManager(blank=True)
    quantity = models.PositiveIntegerField(blank=True, null=True)

    seo_description = models.CharField("SEO-опис", max_length=200, blank=True)

    created = models.DateTimeField('Дата створення', auto_now_add=True)
    updated = models.DateTimeField('Остання правка', auto_now=True)

    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, related_name='brand', blank=True, null=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug',),)
        verbose_name = 'товар'
        verbose_name_plural = 'товари'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[str(self.category.slug), str(self.slug), self.pk])


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField('Ім\'я', max_length=80)
    email = models.EmailField('Email', )
    body = models.TextField('Відгук', )
    active = models.BooleanField('Публічний', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Коментар'
        verbose_name_plural = 'Коментарі'
        ordering = ('created',)

    def __str__(self):
        return 'Коментар від {} про товар {} із ID = {}'.format(self.name, self.product.name, self.product.pk)

shop/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body', )


class SearchForm(forms.Form):
    query = forms.CharField()

shop/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from . import models, forms
from cart.forms import CartAddProductForm
from cart.cart import Cart  # need add for normal cart work
from django.contrib.postgres.search import SearchVector


def product_list(request, category_slug=None):
    cart = Cart(request)
    category = None
    products = models.Product.objects.filter(available=True)

    categories = models.Category.objects.all()
    brands = models.Brand.objects.all()

    if category_slug:
        category = get_object_or_404(models.Category, slug=category_slug)
        products = products.filter(category=category)

    # paginator work
    paginator = Paginator(products, 16)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'index.html', {
        'category': category,
        'categories': categories,
        'products': products,
        'cart': cart,
        'brands': brands,
        'page_obj': page_obj,
    })


def category_list(request, category_slug):
    """Show's category page"""
    cart = Cart(request)  # need for cart in header works
    category = get_object_or_404(models.Category, slug=category_slug)
    # products = models.Product.objects.filter(category=category, available=True)
    brands = models.Brand.objects.all()

    # get all product by current parent category
    products = models.Product.objects.filter(category__in=category.get_descendants(include_self=True))

    request = request
    if 'price' in request.GET:
        min_price, max_price = request.GET['price'].split(',')
        products = products.filter(price__range=(min_price, max_price))

    if 'brands' in request.GET:
        selected_brands = [int(i) for i in request.GET.getlist('brands')]
        products = products.filter(brand__in=selected_brands)

    if 'categories' in request.GET:
        selected_categories = [int(i) for i in request.GET.getlist('categories')]
        filter_categories = []
        for category_id in selected_categories:
            category_obj = models.Category.objects.filter(id=category_id).first()
            filter_categories.extend(category_obj.get_descendants(include_self=True))
        products = products.filter(category__in=filter_categories)

    # need for menu works
    categories = models.Category.objects.all().order_by('position')

    # paginator work
    paginator = Paginator(products, 24)  # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'category.html', {
        'category': category,
        'categories': categories,
        'products': products,
        'cart': cart,
        'page_obj': page_obj,
        'brands': brands,
    })


def product_detail(request, pk, slug, category_slug):
    cart = Cart(request)  # need for cart in header works
    product = get_object_or_404(models.Product, id=pk, slug=slug, available=True, )
    cart_product_form = CartAddProductForm()
    categories = models.Category.objects.all().order_by('position')
    brands = models.Brand.objects.all()

    # Список активных комментариев для этой статьи.
    comments = product.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # Пользователь отправил комментарий.
        comment_form = forms.CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей product.
            new_comment.product = product
            # Сохраняем комментарий в базе данных.
            new_comment.save()
    else:
        comment_form = forms.CommentForm()

    return render(request, 'product_detail.html', {
        'product': product,
        'cart_product_form': cart_product_form,
        'categories': categories,
        'category_slug': category_slug,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'cart': cart,
        'brands': brands,
    })


def products_search(request):
    cart = Cart(request)  # need for cart in header works
    form = forms.SearchForm()
    query = None
    results = []
    brands = models.Brand.objects.all()

    if 'query' in request.GET:
        form = forms.SearchForm(request.GET)

    if form.is_valid():
        query = form.cleaned_data['query']
        results = models.Product.objects.annotate(search=SearchVector('name', 'description'), ).filter(search=query)
    return render(request, 'shop/search.html', {
        'form': form,
        'query': query,
        'results': results,
        'brands': brands,
        'cart': cart,
    })

templates/shop/search.html
{% extends "base.html" %}
{% load static %}

{% block title %}Пошук{% endblock %}

{% block content %}

    {% if query %}
        <div id="products-tab" class="wow fadeInUp">
            <div class="container">

                <h1>Товарів містять "{{ query }}"</h1>

                {% with results.count as total_results %}
                    <h3> Знайдено {{ total_results }} результатів</h3>
                {% endwith %}

                <br><br><br><br>

                <div class="tab-content">
                    <div id="grid-view" class="products-grid fade tab-pane in active">
                        <div class="product-grid-holder">
                            <div class="row no-margin">

                                {% for product in results %}
                                    <div class="col-xs-12 col-sm-3 no-margin product-item-holder hover">
                                        <div class="product-item">
                                            {% if product.small_image %}
                                                <div class="image">
                                                    <a href="{{ product.get_absolute_url }}">
                                                        <img alt="{{ product.name }}"
                                                             src="{{ product.small_image.url }}"
                                                             data-echo="{{ product.small_image.url }}"
                                                             style="width: 246px; height: 186px"/>
                                                    </a>
                                                </div>
                                            {% else %}
                                                <div class="image">
                                                    <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                                         data-echo="{% static 'assets/images/products/product-01.jpg' %}"/>
                                                </div>
                                            {% endif %}

                                            <div class="body">
                                                <div class="label-discount clear"></div>
                                                <div class="title">
                                                    <a href="{{ product.get_absolute_url }}">
                                                        {{ product.name }}
                                                    </a>
                                                </div>
                                                {% if product.brand %}
                                                    <div class="brand">{{ product.brand.name }}</div>
                                                {% endif %}
                                            </div>

                                            <div class="prices">
                                                {% if product.old_price %}
                                                    <div class="price-prev">{{ product.old_price }}</div>
                                                {% else %}
                                                    <div class="price-prev"></div>
                                                {% endif %}

                                                <div class="price-current pull-right">
                                                    {{ product.price }} грн
                                                </div>
                                            </div>


                                            <div class="hover-area">
                                                <div class="add-cart-button">
                                                    <a href="{% url 'shop:product_detail' category_slug=product.category.slug pk=product.id slug=product.slug %}"
                                                       class="le-button">
                                                        Детальніше
                                                    </a>
                                                </div>
                                            </div>

                                        </div><!-- /.product-item -->
                                    </div>

                                {% empty %}
                                    <p>Нічого не знайдено</p>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>

                <p><a href="{% url "shop:products_search" %}">Шукати знову</a></p> {% else %}
                {#            <h1>Шукати товари</h1>#}
                {#            <form action="." method="get">#}
                {#                {{ form.as_p }}#}
                {#                <input type="submit" value="Search"></form>#}
            </div>
        </div>

    {% endif %}

    <br><br><br><br>

    {% include 'parts/top_brands.html' %}
{% endblock %}