cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

goza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import ProductsSitemap

sitemaps = {'posts': ProductsSitemap, }

# admin.autodiscover()
# admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),

    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),

    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('tinymce/', include('tinymce.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search/', views.products_search, name='products_search'),
    path('<slug:category_slug>', views.category_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:slug>/<int:pk>/', views.product_detail, name='product_detail'),

]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    def __init__(self, post = None, max_value = None, *args, **kwargs):
        super(CartAddProductForm, self).__init__(post, *args, **kwargs)
        if max_value:
            self.fields['quantity'] = forms.IntegerField(max_value=max_value)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Category


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    categories = Category.objects.all().order_by('position')

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            max_value=item['product'].quantity,
            initial={'quantity': item['quantity'],
                     'update': True}
        )
    return render(request, 'cart.html', {
        'cart': cart,
        'categories': categories,

    })

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ua">
<head>
    <!-- Meta -->
    <meta charset="utf-8">
    <title>{% block title %}Інтернет-магазин GoZa{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <meta name="author" content="GoZa">
    <meta name="robots" content="all">


    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">

    <!-- Customizable CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/colors/dark-green.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.transitions.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">

    <!-- Fonts -->
    <link href='//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Icons/Glyphs -->
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    <!-- HTML5 elements and media queries Support for IE8 : HTML5 shim and Respond.js -->
    <!--[if lt IE 9]>
            <script src="{% static 'assets/js/html5shiv.js' %}"></script>
            <script src="{% static 'assets/js/respond.min.js' %}"></script>
        <![endif]-->
</head>

<body>

<div class="wrapper">

    {% include 'parts/top_nav.html' %}
    {% include 'parts/header.html' %}

    {% block content %}{% endblock %}

    {% include 'parts/footer.html' %}
</div><!-- /.wrapper -->

<!-- JavaScripts placed at the end of the document so the pages load faster -->
<script src="{% static 'assets/js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'assets/js/jquery-migrate-1.2.1.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script src="//maps.google.com/maps/api/js?key=AIzaSyDDZJO4F0d17RnFoi1F2qtw4wn6Wcaqxao&sensor=false&amp;language=ru"></script>
<script src="{% static 'assets/js/gmap3.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-hover-dropdown.min.js' %}"></script>
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/css_browser_selector.min.js' %}"></script>
<script src="{% static 'assets/js/echo.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.easing-1.3.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap-slider.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.raty.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.prettyPhoto.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.customSelect.min.js' %}"></script>
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/buttons.js' %}"></script>
<script src="{% static 'assets/js/scripts.js' %}"></script>

{% block scripts %}

{% endblock %}
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Кошик
{% endblock %}

{% block content %}


    <div class="animate-dropdown">
        <!-- ========================================= BREADCRUMB ========================================= -->
        <div id="top-mega-nav">
            <div class="container">
                <nav>
                    <ul class="inline">
                        <li class="dropdown le-dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-list"></i>категорії товарів
                            </a>
                            <ul class="dropdown-menu">

                                {% for category in categories %}
                                    {% if category.is_root_node %} {# get only root nodes #}
                                        <li>
                                            <a href="{{ category.get_absolute_url }}">
                                                {{ category }}
                                            </a>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            
                            </ul>
                        </li>

                        <li class="breadcrumb-nav-holder">
                            <ul>
                                <li class="breadcrumb-item">
                                    <a href="{% url 'shop:product_list' %}">Головна</a>
                                </li>

                                <li class="breadcrumb-item current gray">
                                    <a>Кошик</a>
                                </li>
                            </ul>
                        </li><!-- /.breadcrumb-nav-holder -->
                    </ul>
                </nav>
            </div><!-- /.container -->
        </div><!-- /#top-mega-nav -->
        <!-- ========================================= BREADCRUMB : END ========================================= -->
    </div>

    <section id="cart-page">
        <div class="container">
            <!-- ========================================= CONTENT ========================================= -->
            <div class="col-xs-12 col-md-9 items-holder no-margin">
                {% for item in cart %}
                    {% with product=item.product %}

                        <!-- /.cart-item START -->

                        <div class="row no-margin cart-item">
                            <div class="col-xs-12 col-sm-2 no-margin">

                                {% if product.small_image %}

                                    <a href="{% url 'shop:product_detail' category_slug=product.category.slug pk=product.id slug=product.slug %}"
                                       class="thumb-holder">
                                        <img class="lazy" alt="" src="{{ product.small_image.url }}"/>
                                    </a>

                                {% else %}

                                    <a href="{% url 'shop:product_detail' category_slug=product.category.slug pk=product.id slug=product.slug %}"
                                       class="thumb-holder">
                                        <img class="lazy" alt="" src="http://placehold.it/73x73"/>
                                    </a>

                                {% endif %}

                            </div>

                            <div class="col-xs-12 col-sm-5">
                                <div class="title">
                                    <a href="{% url 'shop:product_detail' category_slug=product.category.slug pk=product.id slug=product.slug %}">
                                        {{ product.name }}
                                    </a>
                                </div>
                                {% if product.brand %}
                                <div class="brand">{{ product.brand.name }}</div>
                                {% endif %}
                                {% if item.product.quantity %}
                                На складі залишилося {{ item.product.quantity }} штук
                                {% endif %}
                            </div>

                            <div class="col-xs-12 col-sm-3 no-margin">
                                <div class="quantity">

                                    <form action="{% url "cart:cart_add" product.id %}"
                                          method="post">
                                        <div class="form-group">
                                            {{ item.update_quantity_form.quantity }}

                                            {{ item.update_quantity_form.update }}

                                            <input class="btn btn-default" value="Змінити" type="submit">

                                        </div>

                                        {% csrf_token %}

                                    </form>

                                </div>
                            </div>


                            <div class="col-xs-12 col-sm-2 no-margin">
                                <div class="price">
                                    {{ product.price }} грн
                                </div>
                                <a class="close-btn" href="{% url "cart:cart_remove" product.id %}"></a>
                            </div>
                        </div>

                        <!-- /.cart-item -->


                    {% endwith %}
                {% endfor %}
            </div>
            <!-- ========================================= CONTENT : END ========================================= -->

            <!-- ========================================= SIDEBAR ========================================= -->

            <div class="col-xs-12 col-md-3 no-margin sidebar ">
                <div class="widget cart-summary">
                    <h1 class="border">Кошик</h1>
                    <div class="body">
{#                        <ul class="tabled-data no-border inverse-bold">#}
{#                            <li>#}
{#                                <label>Сума</label>#}
{#                                <div class="value pull-right">{{ cart.get_total_price }} грн</div>#}
{#                            </li>#}
{#                            <li>#}
{#                                <label>Доставка</label>#}
{#                                <div class="value pull-right">Безкоштовна</div>#}
{#                            </li>#}
{#                        </ul>#}
                        <ul id="total-price" class="tabled-data inverse-bold no-border">
                            <li>
                                <label>До сплати:</label>
                                <div class="value pull-right" style="font-size: 15px;">{{ cart.get_total_price }} грн
                                </div>
                            </li>
                        </ul>

                        <div class="buttons-holder">
                            <a class="le-button big" href="{% url 'orders:order_create' %}">Створити замовлення</a>
                            <a class="simple-link block" href="{% url 'shop:product_list' %}">Продовжити покупки</a>
                        </div>

                    </div>
                </div><!-- /.widget -->

                {#                <div id="cupon-widget" class="widget">#}
                {#                    <h1 class="border">use coupon</h1>#}
                {#                    <div class="body">#}
                {#                        <form>#}
                {#                            <div class="inline-input">#}
                {#                                <input data-placeholder="enter coupon code" type="text"/>#}
                {#                                <button class="le-button" type="submit">Apply</button>#}
                {#                            </div>#}
                {#                        </form>#}
                {#                    </div>#}
                {#                </div><!-- /.widget -->#}
            </div><!-- /.sidebar -->

            <!-- ========================================= SIDEBAR : END ========================================= -->
        </div>
    </section>
{% endblock %}

templates/coming_soon.html
{% load static %}


{% block title %}GOZA shop {% endblock %}

{% block content %}

    <style>
    body {
        background: #000;
        font-family: Tahoma, Serif, serif;
    }

    h1 {
        text-align: center;
        margin: 50px auto 0 auto;
        font-size: 60px;
        color: #fff;
    }

    img {
        display: block;
        width: 10%;
        margin: 150px auto 0 auto;
    }
    </style>

    <img src="{% static 'img/logo.png' %}" alt="GoZA">

    <h1>
        Coming soon ...
    </h1>




{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block title %}Інтернет-магазин GoZa{% endblock %}

{% block content %}


    {% include 'parts/sidemenu_slider.html' %}
    {% include 'parts/cat_banners.html' %}
    {% include 'parts/tabs.html' %}
    {# include 'parts/bestsellers.html' #}

    {#    {% include 'parts/recentlyviewed.html' %}#}
    {% include 'parts/top_brands.html' %}
{% endblock %}