cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

goza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.sitemaps.views import sitemap
from shop.sitemaps import ProductsSitemap

sitemaps = {'posts': ProductsSitemap, }

# admin.autodiscover()
# admin.site.enable_nav_sidebar = False

urlpatterns = [
    path('admin/', admin.site.urls),

    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('shop.urls', namespace='shop')),

    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('tinymce/', include('tinymce.urls')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('search/', views.products_search, name='products_search'),
    path('<slug:category_slug>', views.category_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:slug>/<int:pk>/', views.product_detail, name='product_detail'),

]

templates/parts/cat_banners.html
{% load static %}

<!-- ========================================= HOME BANNERS ========================================= -->
<section id="banner-holder" class="wow fadeInUp">
    <div class="container">

        {% for cat in categories %}

            {% if cat.available_on_main %}

                <div class="col-xs-12 col-lg-6 {% if not forloop.first  %}text-right{% endif%} no-margin banner">
                    <a href="{{ cat.get_absolute_url }}">

                        <div class="banner-text theblue">
                            <h1>{{ cat.name }}</h1>
                            {#                                <span class="tagline">Опис категорії</span>#}
                        </div>

                        {% if cat.small_image %}
                            <img class="banner-image" alt="{{ cat.name }} GoZa" src="{{ cat.small_image.url }}"
                                 data-echo="{{ cat.small_image.url }}"/>
                        {% else %}
                            <img class="banner-image" alt="GoZa" src="{% static "assets/images/blank.gif" %}"
                                 data-echo="{% static "assets/images/banners/banner-narrow-01.jpg" %}"/>
                        {% endif %}
                    </a>

                </div>
            {% endif %}

        {% endfor %}


    </div><!-- /.container -->
</section><!-- /#banner-holder -->
<!-- ========================================= HOME BANNERS : END ========================================= -->

templates/parts/header.html
{% load static search_block %}

<!-- ============================================================= HEADER ============================================================= -->
<header>
    <div class="container no-padding">
        <div class="col-xs-12 col-sm-12 col-md-3 logo-holder">
            <!-- ============================================================= LOGO ============================================================= -->
            <div class="logo">
                <a href="{% url 'shop:product_list' %}">
                    <img style='transform: scale(1.6); margin: 0 auto; display: block;' alt="Goza" src="{% static 'img/logo.png' %}" width="233" height="54"/>
                </a>
            </div><!-- /.logo -->
            <!-- ============================================================= LOGO : END ============================================================= -->
        </div><!-- /.logo-holder -->

        <div class="col-xs-12 col-sm-12 col-md-6 top-search-holder no-margin">
            <div class="contact-row">
                <div class="phone inline">
                    <i class="fa fa-phone"></i> +380 (50) 990 76 78
                </div>

                <div class="phone inline">
                    <i class="fa fa-phone"></i> +380 (96) 292 50 28
                </div>


                <div class="contact inline">
                    <i class="fa fa-envelope"></i> gozacomua@<span class="le-color">gmail.com</span>
                </div>
            </div><!-- /.contact-row -->
            <!-- ============================================================= SEARCH AREA ============================================================= -->
            <div class="search-area">
                {% search %}
            </div><!-- /.search-area -->
            <!-- ============================================================= SEARCH AREA : END ============================================================= -->
        </div><!-- /.top-search-holder -->

        <div class="col-xs-12 col-sm-12 col-md-3 top-cart-row no-margin">
            <div class="top-cart-row-container">
                <!-- ============================================================= SHOPPING CART DROPDOWN ============================================================= -->
                {% with total_items=cart|length %}


                    {% if cart|length > 0 %}{# check cart items #}

                        <div class="top-cart-holder dropdown animate-dropdown">
                        <div class="basket">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <div class="basket-item-count">
                                <span class="count">{{ total_items }}</span>
                                <img src="{% static 'assets/images/icon-cart.png' %}" alt=""/>
                            </div>

                            <div class="total-price-basket">
                                <span class="lbl">Кошик:</span>
                                <span class="total-price">

                                <span class="value">{{ cart.get_total_price | floatformat:2 }}</span>
                                <span class="sign">грн</span>
                            </span>
                            </div>
                        </a>
                    {% else %}

                        {# if cart empty #}
                        <div class="top-cart-holder animate-dropdown">
                        <div class="basket">
                        <a class="dropdown-toggle" href="{% url "cart:cart_detail" %}">
                            <div class="basket-item-count">
                                <span class="count">0</span>
                                <img src="{% static 'assets/images/icon-cart.png' %}" alt=""/>
                            </div>

                            <div class="total-price-basket">
                                <span class="lbl">Кошик:</span>
                                <span class="total-price">

                                <span class="value">0</span>
                                <span class="sign">грн</span>
                            </span>
                            </div>
                        </a>


                    {% endif %}
                {% endwith %}

                <ul class="dropdown-menu">
                    <li class="checkout">
                        <div class="basket-item">
                            <div class="row">
                                <div class="col-xs-12 col-sm-6 text-center">
                                    <a href="{% url 'cart:cart_detail' %}" class="le-button inverse">Список покупок</a>
                                </div>
                                <div class="col-xs-12 col-sm-6 text-center">
                                    <a href="{% url "orders:order_create" %}" class="le-button">Створити замовленя</a>
                                </div>
                            </div>
                        </div>
                    </li>

                </ul>
                </div><!-- /.basket -->
                </div><!-- /.top-cart-holder -->
                </div><!-- /.top-cart-row-container -->
                <!-- ============================================================= SHOPPING CART DROPDOWN : END ============================================================= -->
                </div><!-- /.top-cart-row -->
            </div><!-- /.container -->
</header>
<!-- ============================================================= HEADER : END ============================================================= -->

templates/parts/recentlyviewed.html
{% load static %}

<!-- ========================================= RECENTLY VIEWED ========================================= -->
<section id="recently-reviewd" class="wow fadeInUp">
    <div class="container">
        <div class="carousel-holder hover">

            <div class="title-nav">
                <h2 class="h1">Recently Viewed</h2>
                <div class="nav-holder">
                    <a href="#prev" data-target="#owl-recently-viewed"
                       class="slider-prev btn-prev fa fa-angle-left"></a>
                    <a href="#next" data-target="#owl-recently-viewed"
                       class="slider-next btn-next fa fa-angle-right"></a>
                </div>
            </div><!-- /.title-nav -->

            <div id="owl-recently-viewed" class="owl-carousel product-grid-holder">
                <div class="no-margin carousel-item product-item-holder size-small hover">
                    <div class="product-item">
                        <div class="ribbon red"><span>sale</span></div>
                        <div class="image">
                            <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                 data-echo="{% static 'assets/images/products/product-11.jpg' %}"/>
                        </div>
                        <div class="body">
                            <div class="title">
                                <a href="single-product.html">LC-70UD1U 70" class aquos 4K ultra HD</a>
                            </div>
                            <div class="brand">Sharp</div>
                        </div>
                        <div class="prices">
                            <div class="price-current text-right">$1199.00</div>
                        </div>
                        <div class="hover-area">
                            <div class="add-cart-button">
                                <a href="single-product.html" class="le-button">Add to Cart</a>
                            </div>
                            <div class="wish-compare">
                                <a class="btn-add-to-wishlist" href="#">Add to Wishlist</a>
                                <a class="btn-add-to-compare" href="#">Compare</a>
                            </div>
                        </div>
                    </div><!-- /.product-item -->
                </div><!-- /.product-item-holder -->

                <div class="no-margin carousel-item product-item-holder size-small hover">
                    <div class="product-item">
                        <div class="ribbon blue"><span>new!</span></div>
                        <div class="image">
                            <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                 data-echo="{% static 'assets/images/products/product-12.jpg' %}"/>
                        </div>
                        <div class="body">
                            <div class="title">
                                <a href="single-product.html">cinemizer OLED 3D virtual reality TV Video</a>
                            </div>
                            <div class="brand">zeiss</div>
                        </div>
                        <div class="prices">
                            <div class="price-current text-right">$1199.00</div>
                        </div>
                        <div class="hover-area">
                            <div class="add-cart-button">
                                <a href="single-product.html" class="le-button">Add to cart</a>
                            </div>
                            <div class="wish-compare">
                                <a class="btn-add-to-wishlist" href="#">Add to Wishlist</a>
                                <a class="btn-add-to-compare" href="#">Compare</a>
                            </div>
                        </div>
                    </div><!-- /.product-item -->
                </div><!-- /.product-item-holder -->

                <div class=" no-margin carousel-item product-item-holder size-small hover">
                    <div class="product-item">

                        <div class="image">
                            <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                 data-echo="{% static 'assets/images/products/product-13.jpg' %}"/>
                        </div>
                        <div class="body">
                            <div class="title">
                                <a href="single-product.html">s2340T23" full HD multi-Touch Monitor</a>
                            </div>
                            <div class="brand">dell</div>
                        </div>
                        <div class="prices">
                            <div class="price-current text-right">$1199.00</div>
                        </div>
                        <div class="hover-area">
                            <div class="add-cart-button">
                                <a href="single-product.html" class="le-button">Add to cart</a>
                            </div>
                            <div class="wish-compare">
                                <a class="btn-add-to-wishlist" href="#">Add to Wishlist</a>
                                <a class="btn-add-to-compare" href="#">Compare</a>
                            </div>
                        </div>
                    </div><!-- /.product-item -->
                </div><!-- /.product-item-holder -->

                <div class=" no-margin carousel-item product-item-holder size-small hover">
                    <div class="product-item">
                        <div class="ribbon blue"><span>new!</span></div>
                        <div class="image">
                            <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                 data-echo="{% static 'assets/images/products/product-14.jpg' %}"/>
                        </div>
                        <div class="body">
                            <div class="title">
                                <a href="single-product.html">kardon BDS 7772/120 integrated 3D</a>
                            </div>
                            <div class="brand">harman</div>
                        </div>
                        <div class="prices">
                            <div class="price-current text-right">$1199.00</div>
                        </div>
                        <div class="hover-area">
                            <div class="add-cart-button">
                                <a href="single-product.html" class="le-button">Add to cart</a>
                            </div>
                            <div class="wish-compare">
                                <a class="btn-add-to-wishlist" href="#">Add to Wishlist</a>
                                <a class="btn-add-to-compare" href="#">Compare</a>
                            </div>
                        </div>
                    </div><!-- /.product-item -->
                </div><!-- /.product-item-holder -->

                <div class=" no-margin carousel-item product-item-holder size-small hover">
                    <div class="product-item">
                        <div class="ribbon green"><span>bestseller</span></div>
                        <div class="image">
                            <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                 data-echo="{% static 'assets/images/products/product-15.jpg' %}"/>
                        </div>
                        <div class="body">
                            <div class="title">
                                <a href="single-product.html">netbook acer travel B113-E-10072</a>
                            </div>
                            <div class="brand">acer</div>
                        </div>
                        <div class="prices">
                            <div class="price-current text-right">$1199.00</div>
                        </div>
                        <div class="hover-area">
                            <div class="add-cart-button">
                                <a href="single-product.html" class="le-button">Add to cart</a>
                            </div>
                            <div class="wish-compare">
                                <a class="btn-add-to-wishlist" href="#">Add to Wishlist</a>
                                <a class="btn-add-to-compare" href="#">Compare</a>
                            </div>
                        </div>
                    </div><!-- /.product-item -->
                </div><!-- /.product-item-holder -->

                <div class=" no-margin carousel-item product-item-holder size-small hover">
                    <div class="product-item">

                        <div class="image">
                            <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                 data-echo="{% static 'assets/images/products/product-16.jpg' %}"/>
                        </div>
                        <div class="body">
                            <div class="title">
                                <a href="single-product.html">iPod touch 5th generation,64GB, blue</a>
                            </div>
                            <div class="brand">apple</div>
                        </div>
                        <div class="prices">
                            <div class="price-current text-right">$1199.00</div>
                        </div>
                        <div class="hover-area">
                            <div class="add-cart-button">
                                <a href="single-product.html" class="le-button">Add to cart</a>
                            </div>
                            <div class="wish-compare">
                                <a class="btn-add-to-wishlist" href="#">Add to Wishlist</a>
                                <a class="btn-add-to-compare" href="#">Compare</a>
                            </div>
                        </div>
                    </div><!-- /.product-item -->
                </div><!-- /.product-item-holder -->

                <div class=" no-margin carousel-item product-item-holder size-small hover">
                    <div class="product-item">

                        <div class="image">
                            <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                 data-echo="{% static 'assets/images/products/product-13.jpg' %}"/>
                        </div>
                        <div class="body">
                            <div class="title">
                                <a href="single-product.html">s2340T23" full HD multi-Touch Monitor</a>
                            </div>
                            <div class="brand">dell</div>
                        </div>
                        <div class="prices">
                            <div class="price-current text-right">$1199.00</div>
                        </div>
                        <div class="hover-area">
                            <div class="add-cart-button">
                                <a href="single-product.html" class="le-button">Add to cart</a>
                            </div>
                            <div class="wish-compare">
                                <a class="btn-add-to-wishlist" href="#">Add to Wishlist</a>
                                <a class="btn-add-to-compare" href="#">Compare</a>
                            </div>
                        </div>
                    </div><!-- /.product-item -->
                </div><!-- /.product-item-holder -->

                <div class=" no-margin carousel-item product-item-holder size-small hover">
                    <div class="product-item">
                        <div class="ribbon blue"><span>new!</span></div>
                        <div class="image">
                            <img alt="" src="{% static 'assets/images/blank.gif' %}"
                                 data-echo="{% static 'assets/images/products/product-14.jpg' %}"/>
                        </div>
                        <div class="body">
                            <div class="title">
                                <a href="single-product.html">kardon BDS 7772/120 integrated 3D</a>
                            </div>
                            <div class="brand">harman</div>
                        </div>
                        <div class="prices">
                            <div class="price-current text-right">$1199.00</div>
                        </div>
                        <div class="hover-area">
                            <div class="add-cart-button">
                                <a href="single-product.html" class="le-button">Add to cart</a>
                            </div>
                            <div class="wish-compare">
                                <a class="btn-add-to-wishlist" href="#">Add to Wishlist</a>
                                <a class="btn-add-to-compare" href="#">Compare</a>
                            </div>
                        </div>
                    </div><!-- /.product-item -->
                </div><!-- /.product-item-holder -->
            </div><!-- /#recently-carousel -->

        </div><!-- /.carousel-holder -->
    </div><!-- /.container -->
</section><!-- /#recently-reviewd -->
<!-- ========================================= RECENTLY VIEWED : END ========================================= -->

templates/parts/sidemenu_slider.html
{% load static %}
{% load mptt_tags %}

<div id="top-banner-and-menu">
    <div class="container">
        <div class="col-xs-12 col-sm-4 col-md-3 sidemenu-holder">
            <!-- ================================== TOP NAVIGATION ================================== -->
            <div class="side-menu animate-dropdown">
                <div class="head"><i class="fa fa-list"></i>Категорії</div>
                <nav class="yamm megamenu-horizontal" role="navigation">
                    <ul class="nav">


                        {% recursetree categories %}

                            {% if not node.is_leaf_node %}
                                <li class="dropdown menu-item">
                                    <a class="dropdown-toggle" data-toggle="dropdown" href="/{{ node.slug }}">
                                        {{ node.name }}
                                    </a>
                                    <ul class="dropdown-menu mega-menu">
                                        <li class="yamm-content">
                                            <div class="row">

                                                <div class="col-md-4">
                                                    <ul class="list-unstyled">
                                                        {{ children }}
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </li>



                            {% else %}
                                <li class="menu-item">
                                    <a href="{% url 'shop:product_list_by_category' category_slug=node.slug %}">
                                        {{ node.name }}
                                    </a>
                                </li>
                            {% endif %}

                        {% endrecursetree %}

                    </ul><!-- /.nav -->
                </nav><!-- /.megamenu-horizontal -->
            </div><!-- /.side-menu -->
            <!-- ================================== TOP NAVIGATION : END ================================== -->
        </div><!-- /.sidemenu-holder -->

        <div class="col-xs-12 col-sm-8 col-md-9 homebanner-holder">
            <!-- ========================================== SECTION – HERO ========================================= -->
            <div id="hero">
                <div id="owl-main" class="owl-carousel owl-inner-nav owl-ui-sm">

                    <div class="item"
                         style="background-image: url({% static 'assets/images/sliders/slider01.jpg' %});">
                        <div class="container-fluid">
                            <div class="caption vertical-center text-left">
                                <div class="big-text fadeInDown-1">
                                    Купуйте вигідно<span class="big"></span>
                                </div>

                                <div class="excerpt fadeInDown-2">
                                    Та за розумними цінами!
                                </div>

{#                                <div class="small fadeInDown-2">#}
{#                                    Ваші данні в беспеці#}
{#                                </div>#}


{#                                <div class="button-holder fadeInDown-3">#}
{#                                    <a href="{% url 'register' %}" class="big le-button ">Реєстрація</a>#}
{#                                </div>#}


                            </div><!-- /.caption -->
                        </div><!-- /.container-fluid -->
                    </div><!-- /.item -->

{#                    <div class="item"#}
{#                         style="background-image: url({% static 'assets/images/sliders/slider02.jpg' %});">#}
{#                        <div class="container-fluid">#}
{#                            <div class="caption vertical-center text-left">#}
{#                                <div class="big-text fadeInDown-1">#}
{#                                    Want a<span class="big"><span class="sign">$</span>200</span>Discount?#}
{#                                </div>#}
{##}
{#                                <div class="excerpt fadeInDown-2">#}
{#                                    on selected <br>desktop pcs<br>#}
{#                                </div>#}
{#                                <div class="small fadeInDown-2">#}
{#                                    terms and conditions apply#}
{#                                </div>#}
{#                                <div class="button-holder fadeInDown-3">#}
{#                                    <a href="single-product.html" class="big le-button ">shop now</a>#}
{#                                </div>#}
{#                            </div><!-- /.caption -->#}
{#                        </div><!-- /.container-fluid -->#}
{#                    </div><!-- /.item -->#}

                </div><!-- /.owl-carousel -->
            </div>
            <!-- ========================================= SECTION – HERO : END ========================================= -->
        </div><!-- /.homebanner-holder -->
    </div><!-- /.container -->
</div><!-- /#top-banner-and-menu -->

templates/parts/top_brands.html
{% load static %}

<!-- ========================================= TOP BRANDS ========================================= -->
<section id="top-brands" class="wow fadeInUp">
    <div class="container">
        <div class="carousel-holder">

            <div class="title-nav">
                <h1>Виробники</h1>
                <div class="nav-holder">
                    <a href="#prev" data-target="#owl-brands" class="slider-prev btn-prev fa fa-angle-left"></a>
                    <a href="#next" data-target="#owl-brands" class="slider-next btn-next fa fa-angle-right"></a>
                </div>
            </div><!-- /.title-nav -->

            <div id="owl-brands" class="owl-carousel brands-carousel">

                {% if brands %}

                    {% for brand in brands %}
                        <div class="carousel-item">
{#                            <a href="#">#}
                                <img alt="" src="{{ brand.image.url }}"/>
{#                            </a>#}
                        </div><!-- /.carousel-item -->
                    {% endfor %}

                {% else %}
                    <div class="carousel-item">
                        <a href="#">
                            <img alt="" src="{% static 'assets/images/brands/brand-01.jpg' %}"/>
                        </a>
                    </div><!-- /.carousel-item -->
                {% endif %}


            </div><!-- /.brands-caresoul -->

        </div><!-- /.carousel-holder -->
    </div><!-- /.container -->
</section><!-- /#top-brands -->
<!-- ========================================= TOP BRANDS : END ========================================= -->

templates/parts/top_nav.html
<!-- ============================================================= TOP NAVIGATION ============================================================= -->
<nav class="top-bar animate-dropdown">
    <div class="container">

        <div class="col-xs-12 col-sm-6 no-margin">
            <ul>
                <li><a href="{% url 'shop:product_list' %}">Головна</a></li>
                <li><a href="{% url 'cart:cart_detail' %}">Кошик</a></li>
{#                <li><a href="#">Новини</a></li>#}
    {#                <li><a href="#">Запитання / Відповідь</a></li>#}
    {#                <li><a href="#">Контакти</a></li>#}
            </ul>
        </div><!-- /.col -->

        <div class="col-xs-12 col-sm-6 no-margin">
            <ul class="right">

{#                <li>#}
{#                    <a href="{% url 'register' %}">Реєстрація</a>#}
{#                </li>#}
{##}
{#                <li>#}
{#                    <a href="{% url 'login' %}">Вхід</a>#}
{#                </li>#}

                <li>
                    Вітаємо!
                </li>
            </ul>
        </div><!-- /.col -->
    </div><!-- /.container -->
</nav><!-- /.top-bar -->
<!-- ============================================================= TOP NAVIGATION : END ============================================================= -->